environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - ps: choco install maven
  - cmd: SET PATH=C:\tools\apache-maven-3.3.3\bin;%JAVA_HOME%\bin;%PATH%
  - mvn --version
build_script:
  - mvn package
artifacts:
  - path: redpen-distribution/target/*
cache:
  - C:\Users\appveyor\.m2
