version: 2
jobs:
  build:
    docker:
       - image: circleci/openjdk:11
     working_directory: ~/repo
    environment:
       MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports
