
pipeline:
    - name: Set Version
      command: mvn versions:set -DnewVersion=$REDPEN_VERSION
    - name: Add Files to the Next Changes
      command: git add pom.xml; git add **/*.xml
    - name: Commit Version Changes
      command: git commit -m "Bump version $REDPEN_VERSION"
    - name: Delopy to Sonatype
      command: mvn clean deploy -DperformRelease --settings ~/.m2/settings.xml
    - name: Create Release Tag
      command: git tag -a redpen-$REDPEN_VERSION -m "RedPen release $REDPEN_VERSION"
    - name: Set the snapshot version of next release 
      command: mvn versions:set -DnewVersion=$REDPEN_NEW_VERSION-SNAPSHOT
    - name: Commit Version Changes
      command: git commit -m "Update versions for next release"

cleanup:
  - name: Remove temporary files
    command: git clean -f
